CREATE TABLE IF NOT EXISTS USERS
(
    ID       INTEGER AUTO_INCREMENT,
    LOGIN    CHARACTER VARYING(20) NOT NULL,
    EMAIL    CHARACTER VARYING(50) NOT NULL,
    NAME     CHARACTER VARYING(50),
    BIRTHDAY DATE,
    CONSTRAINT USERS_PK
    PRIMARY KEY (ID)
);