CREATE TABLE IF NOT EXISTS USERS
(
    ID       INTEGER AUTO_INCREMENT,
    LOGIN    CHARACTER VARYING(20) NOT NULL,
    EMAIL    CHARACTER VARYING(50) NOT NULL,
    NAME     CHARACTER VARYING(50),
    BIRTHDAY DATE,
    CONSTRAINT USERS_PK
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS FRIENDSHIP
(
    FROM_USER_ID INTEGER     NOT NULL,
    TO_USER_ID   INTEGER     NOT NULL,
    STATUS BOOLEAN NOT NULL,
    CONSTRAINT FRIENDSHIP_PK
    PRIMARY KEY (FROM_USER_ID, TO_USER_ID)
);